export const userLoginConstants={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
}
export const userUpdateConstants = {
    UPDATE_REQUEST:'UPDATE_REQUEST',
    UPDATE_FAILURE:'UPDATE_FAILURE',
    UPDATE_SUCCESS:'UPDATE_SUCCESS',  
}


export const emailConstants = {
    EMAIL_REQUEST:'EMAIL_REQUEST',
    EMAIL_FAILURE:'EMAIL_FAILURE',
    EMAIL_SUCCESS:'EMAIL_SUCCESS',  
}

export const otpConstants = {
    OTP_REQUEST:'OTP_REQUEST',
    OTP_FAILURE:'OTP_FAILURE',
    OTP_SUCCESS:'OTP_SUCCESS',  
}

export const adminCreateProductConstants = {
    ADMIN_CREATEPRODUCT_REQUEST:'ADMIN_CREATEPRODUCT_REQUEST',
    ADMIN_CREATEPRODUCT_FAILURE:'ADMIN_CREATEPRODUCT_FAILURE',
    ADMIN_CREATEPRODUCT_SUCCESS:'ADMIN_CREATEPRODUCT_SUCCESS',    
}
export const adminCreateCategoryConstants = {
    ADMIN_CREATEPRODUCT_REQUEST:'ADMIN_CREATECATEGORY_REQUEST',
    ADMIN_CREATEPRODUCT_FAILURE:'ADMIN_CREATECATEGORY_FAILURE',
    ADMIN_CREATEPRODUCT_SUCCESS:'ADMIN_CREATECATEGORY_SUCCESS',    
}
export const adminUpdateProductConstants = {
    ADMIN_UPDATEPRODUCT_REQUEST:'ADMIN_UPDATEPRODUCT_REQUEST',
    ADMIN_UPDATEPRODUCT_FAILURE:'ADMIN_UPDATEPRODUCT_FAILURE',
    ADMIN_UPDATEPRODUCT_SUCCESS:'ADMIN_UPDATEPRODUCT_SUCCESS',    
}
export const adminUpdateCategoryConstants = {
    ADMIN_UPDATECATEGORY_REQUEST:'ADMIN_UPDATECATEGORY_REQUEST',
    ADMIN_UPDATECATEGORY_FAILURE:'ADMIN_UPDATECATEGORY_FAILURE',
    ADMIN_UPDATECATEGORY_SUCCESS:'ADMIN_UPDATECATEGORY_SUCCESS',    
}

export const adminRecentOrderConstants = {
    ADMIN_RECENTORDER_REQUEST:'ADMIN_RECENTORDER_REQUEST',
    ADMIN_RECENTORDER_FAILURE:'ADMIN_RECENTORDER_FAILURE',
    ADMIN_RECENTORDER_SUCCESS:'ADMIN_RECENTORDER_SUCCESS',    
}

export const adminGetUserInfoConstants = {
    ADMIN_USER_INFO_REQUEST:'ADMIN_USER_INFO_REQUEST',
    ADMIN_USER_INFO_FAILURE:'ADMIN_USER_INFO_FAILURE',
    ADMIN_USER_INFO_SUCCESS:'ADMIN_USER_INFO_SUCCESS',    
}

export const adminDeleteRecentOrderConstants = {
    ADMIN_DELETE_RECENT_ORDER_REQUEST:'ADMIN_DELETE_RECENT_ORDER_REQUEST',
    ADMIN_DELETE_RECENT_ORDER_FAILURE:'ADMIN_DELETE_RECENT_ORDER_FAILURE',
    ADMIN_DELETE_RECENT_ORDER_SUCCESS:'ADMIN_DELETE_RECENT_ORDER_SUCCESS',    
}

export const adminDeleteCustomerConstants = {
    ADMIN_DELETE_CUSTOMER_REQUEST:'ADMIN_DELETE_CUSTOMER_REQUEST',
    ADMIN_DELETE_CUSTOMER_FAILURE:'ADMIN_DELETE_CUSTOMER_FAILURE',
    ADMIN_DELETE_CUSTOMER_SUCCESS:'ADMIN_DELETE_CUSTOMER_SUCCESS',    
}

export const adminDeleteProductConstants = {
    ADMIN_DELETE_PRODUCT_REQUEST:'ADMIN_DELETE_PRODUCT_REQUEST',
    ADMIN_DELETE_PRODUCT_FAILURE:'ADMIN_DELETE_PRODUCT_FAILURE',
    ADMIN_DELETE_PRODUCT_SUCCESS:'ADMIN_DELETE_PRODUCT_SUCCESS',    
}

export const adminDeleteCategoryConstants = {
    ADMIN_DELETE_CATEGORY_REQUEST:'ADMIN_DELETE_CATEGORY_REQUEST',
    ADMIN_DELETE_CATEGORY_FAILURE:'ADMIN_DELETE_CATEGORY_FAILURE',
    ADMIN_DELETE_CATEGORY_SUCCESS:'ADMIN_DELETE_CATEGORY_SUCCESS',    
}

export const adminCustomersConstants = {
    ADMIN_CUSTOMERS_REQUEST:'ADMIN_CUSTOMERS_REQUEST',
    ADMIN_CUSTOMERS_FAILURE:'ADMIN_CUSTOMERS_FAILURE',
    ADMIN_CUSTOMERS_SUCCESS:'ADMIN_CUSTOMERS_SUCCESS',    
}
export const adminAllOrdersConstant = {
    ADMIN_ALLORDERS_REQUEST:'ADMIN_ALLORDERS_REQUEST',
    ADMIN_ALLORDERS_FAILURE:'ADMIN_ALLORDERS_FAILURE',
    ADMIN_ALLORDERS_SUCCESS:'ADMIN_ALLORDERS_SUCCESS',    
}

export const adminAllCategoryConstant = {
    ADMIN_CATEGORY_REQUEST:'ADMIN_CATEGORY_REQUEST',
    ADMIN_CATEGORY_FAILURE:'ADMIN_CATEGORY_FAILURE',
    ADMIN_CATEGORY_SUCCESS:'ADMIN_CATEGORY_SUCCESS',    
}

export const adminAllCategoryParentConstant = {
    ADMIN_ALL_CATEGORY_REQUEST:'ADMIN_ALL_CATEGORY_REQUEST',
    ADMIN_ALL_CATEGORY_FAILURE:'ADMIN_ALL_CATEGORY_FAILURE',
    ADMIN_ALL_CATEGORY_SUCCESS:'ADMIN_ALL_CATEGORY_SUCCESS',    
}


export const adminAllProductConstant = {
    ADMIN_PRODUCTS_REQUEST:'ADMIN_PRODUCTS_REQUEST',
    ADMIN_PRODUCTS_FAILURE:'ADMIN_PRODUCTS_FAILURE',
    ADMIN_PRODUCTS_SUCCESS:'ADMIN_PRODUCTS_SUCCESS',    
}

export const getUserOrdersConstant = {
    USER_ORDERS_REQUEST:'USER_ORDERS_REQUEST',
    USER_ORDERS_FAILURE:'USER_ORDERS_FAILURE',
    USER_ORDERS_SUCCESS:'USER_ORDERS_SUCCESS',    
}
export const setPageConstant = {
    PAGE_REQUEST:'PAGE_REQUEST',
    PAGE_FAILURE:'PAGE_FAILURE',
    PAGE_SUCCESS:'PAGE_SUCCESS',    
}

export const googleLoginConstant = {
    GOOGLE_LOGIN_REQUEST:'GOOGLE_LOGIN_REQUEST',
    GOOGLE_LOGIN_FAILURE:'GOOGLE_LOGIN_FAILURE',
    GOOGLE_LOGIN_SUCCESS:'GOOGLE_LOGIN_SUCCESS',    
}

export const changeStatusConstant = {
    CHANGE_STATUS_REQUEST:'CHANGE_STATUS_REQUEST',
    CHANGE_STATUS_FAILURE:'CHANGE_STATUS_FAILURE',
    CHANGE_STATUS_SUCCESS:'CHANGE_STATUS_SUCCESS',    
}

export const createCouponConstant = {
    CREATE_COUPON_REQUEST:'CREATE_COUPON_REQUEST',
    CREATE_COUPON_FAILURE:'CREATE_COUPON_FAILURE',
    CREATE_COUPON_SUCCESS:'CREATE_COUPON_SUCCESS',    
}

export const deleteCouponConstant = {
    DELETE_COUPON_REQUEST:'DELETE_COUPON_REQUEST',
    DELETE_COUPON_FAILURE:'DELETE_COUPON_FAILURE',
    DELETE_COUPON_SUCCESS:'DELETE_COUPON_SUCCESS',    
}

export const getCouponConstant = {
    GET_COUPON_REQUEST:'GET_COUPON_REQUEST',
    GET_COUPON_FAILURE:'GET_COUPON_FAILURE',
    GET_COUPON_SUCCESS:'GET_COUPON_SUCCESS',    
}